### ISSUE TITLE
Unable to start nodejs client

### ISSUE THREAD

**Issue by ChristianGrieger** [nimiq-network/core#233]
Hey nimiq,

i am new to this all and just try to get the nodejs client to run but always get this error when i try to start it. Maybe you could give me a short hint what i am doing wrong?

```
node index.js --host coin.christiangrieger.de --port 9988 --key "/etc/letsencrypt/live/coin.christiangrieger.de/privkey.pem" --cert "/etc/letsencrypt/live/coin.christiangrieger.de/cert.pem"
/root/nimiqcore/dist/node.js:1
(function (exports, require, module, __filename, __dirname) { module.exports={};const atob=require("atob"),btoa=require("btoa");global.Class={register:e=>{module.exports[e.prototype.constructor.name]=e}};class LogNative{constructor(){this._global_level=Log.TRACE;this._tag_levels={};this._chalk=require("chalk")}isLoggable(e,t){return e&&this._tag_levels[e]?this._tag_levels[e]<=t:this._global_level<=t}setLoggable(e,t){this._tag_levels[e]=t}msg(e,t,s){if(!this.isLoggable(t,e))return;t&&t.name&&(t=t.name);t&&s.unshift(t+":");let i=`[${Log.Level.toStringTag(e)} ${(new Date).toTimeString().substr(0,8)}] `;const r=this._chalk;e>=Log.ERROR?console.log(i+r.red(s.join(" "))):e>=Log.WARNING?console.log(i+r.yellow(s.join(" "))):e>=Log.INFO?console.log(i+r.cyan(s.join(" "))):e>=Log.DEBUG?console.log(i+r.magenta(s.join(" "))):e<=Log.TRACE?console.trace(i+s.join(" ")):console.log(i+s.join(" "))}}Class.register(LogNative);class Log{static get instance(){Log._instance||(Log._instance=new Log(n

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/nimiqcore/clients/nodejs/index.js:1:77)
```

Now using node v8.9.1 (npm v5.5.1) and get this error:

```
node index.js --host coin.christiangrieger.de --port 9988 --key "/etc/letsencrypt/live/coin.christiangrieger.de/privkey.pem" --cert "/etc/letsencrypt/live/coin.christiangrieger.de/cert.pem"
Nimiq NodeJS Client starting (host=coin.christiangrieger.de, port=9988, miner=false, passive=false)
(node:20862) LevelUPError: Failed to require LevelDOWN (The module '/root/nimiqcore/node_modules/leveldown/build/Release/leveldown.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).). Try `npm install leveldown` if it's missing
    at requireError (/root/nimiqcore/node_modules/levelup/lib/leveldown.js:37:10)
    at getLevelDOWN (/root/nimiqcore/node_modules/levelup/lib/leveldown.js:31:11)
    at LevelUP.open (/root/nimiqcore/node_modules/levelup/lib/levelup.js:112:34)
    at new LevelUP (/root/nimiqcore/node_modules/levelup/lib/levelup.js:84:8)
    at LevelUP (/root/nimiqcore/node_modules/levelup/lib/levelup.js:45:44)
    at ConsensusDB.connect (/root/nimiqcore/node_modules/jungle-db/dist/node.js:6198:29)
    at ConsensusDB._init (/root/nimiqcore/dist/node.js:1:136296)
    at new ConsensusDB (/root/nimiqcore/dist/node.js:1:136188)
    at Function.get (/root/nimiqcore/dist/node.js:1:136077)
    at Function.full (/root/nimiqcore/dist/node.js:1:136545)
(node:20862) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitWarning (internal/process/promises.js:78:15)
    at emitPendingUnhandledRejections (internal/process/promises.js:95:11)
    at runMicrotasksCallback (internal/process/next_tick.js:124:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by sisou** [comment]
Did you do a "npm install" without errors in both the main "core" directory AND the "clients/nodejs" directory?

**Comment by sisou** [comment]
Oh, and you should do a "npm run build" in the main "nimiqcore" directory to regenerate the files.

Disclaimer: The "master" branch is in active development for the next, unreleased version of the testnet! To connect to the current betanet, use the "betanet" branch.

**Comment by ChristianGrieger** [comment]
Yes i did it in the main folder in the client nodejs folder and the src main platform nodejs folder :/ 
I will try to do it with the betanet branch again and see if that works :) thank you
