### ISSUE TITLE
Node Client: invalid ELF header error 

### ISSUE THREAD

**Issue by jsappme** [nimiq-network/core#249]
```
Starting process with command `node index.js --host=nimik.me --port=8080 --key=private.key --cert=certificate.crt --miner=1`
2017-11-27T22:39:03.314269+00:00 app[web.1]: Nimiq NodeJS Client starting (host=nimik.me, port=8080, miner=true, passive=false)
2017-11-27T22:39:05.984310+00:00 app[web.1]: trying binaryen method: native-wasm
2017-11-27T22:39:05.984801+00:00 app[web.1]: asynchronously preparing wasm
2017-11-27T22:39:05.985146+00:00 app[web.1]: binaryen method succeeded.
2017-11-27T22:39:06.095635+00:00 app[web.1]: [D 22:39:06] WebSocketConnector: WebSocketConnector listening on port 8080
2017-11-27T22:39:06.137251+00:00 app[web.1]: [I 22:39:06] Node: Wallet initialized for address NQ74 HSUX BX64 NC6V YHQ7 C0C7 RFMF HFS4 AT13.
2017-11-27T22:39:06.140323+00:00 app[web.1]: Error: /app/dist/nimiq_node.node: invalid ELF header
2017-11-27T22:39:06.140324+00:00 app[web.1]:     at Object.Module._extensions..node (module.js:664:18)
2017-11-27T22:39:06.140325+00:00 app[web.1]:     at Module.load (module.js:554:32)
2017-11-27T22:39:06.140326+00:00 app[web.1]:     at tryModuleLoad (module.js:497:12)
2017-11-27T22:39:06.140326+00:00 app[web.1]:     at Function.Module._load (module.js:489:3)
2017-11-27T22:39:06.140327+00:00 app[web.1]:     at Module.require (module.js:579:17)
2017-11-27T22:39:06.140328+00:00 app[web.1]:     at require (internal/module.js:11:18)
2017-11-27T22:39:06.140328+00:00 app[web.1]:     at new MinerWorkerPool (/app/dist/node.js:1:223988)
2017-11-27T22:39:06.140329+00:00 app[web.1]:     at new Miner (/app/dist/node.js:1:205715)
2017-11-27T22:39:06.140329+00:00 app[web.1]:     at __dirname (/app/index.js:50:19)
2017-11-27T22:39:06.140330+00:00 app[web.1]:     at <anonymous>
```

**Comment by sisou** [comment]
First result for googling "invalid ELF header":
https://stackoverflow.com/questions/29994411/invalid-elf-header-when-using-the-nodejs-ref-module-on-aws-lambda

From there:
> This happens when you build on one architecture and then attempt to use the same built addon on a different architecture (or platform in some cases).

Ergo, you should rerun `npm run build` in the environment that you actually want to run nimiq.

**Comment by jsappme** [comment]
thanks @sisou
