### ISSUE TITLE
Transaction already closed error

### ISSUE THREAD

**Issue by jsappme** [nimiq-network/core#252]
With the node js client, those error messages show up sometimes. It does not lose the consensus but the miner runs on the same block forever and does not get notice of new blocks. Any idea why?

The miner keeps mining the last block and will receive the award if it finds it. Next it moved the next old block. So it's out of sync with the current blockchain but keeps mining like nothing happens.

```
Watchdog timer aborted transaction Transaction {
2017-11-30T00:44:31.742364+00:00 app[web.1]:   _id: 42399,
2017-11-30T00:44:31.742365+00:00 app[web.1]:   _objectStore: 
2017-11-30T00:44:31.742366+00:00 app[web.1]:    ObjectStore {
2017-11-30T00:44:31.742366+00:00 app[web.1]:      __backend: 
2017-11-30T00:44:31.742367+00:00 app[web.1]:       LevelDBBackend {
2017-11-30T00:44:31.742367+00:00 app[web.1]:         _db: [ConsensusDB],
2017-11-30T00:44:31.742368+00:00 app[web.1]:         _tableName: 'Accounts',
2017-11-30T00:44:31.742368+00:00 app[web.1]:         _indices: Map {},
2017-11-30T00:44:31.742369+00:00 app[web.1]:         _codec: AccountsTreeStoreCodec {},
2017-11-30T00:44:31.742370+00:00 app[web.1]:         _dbBackend: [EventEmitter] },
2017-11-30T00:44:31.742370+00:00 app[web.1]:      _db: 
2017-11-30T00:44:31.742371+00:00 app[web.1]:       ConsensusDB {
2017-11-30T00:44:31.742371+00:00 app[web.1]:         _databaseDir: 'full-consensus/',
2017-11-30T00:44:31.742372+00:00 app[web.1]:         _dbVersion: 3,
2017-11-30T00:44:31.742372+00:00 app[web.1]:         _onUpgradeNeeded: undefined,
2017-11-30T00:44:31.742373+00:00 app[web.1]:         _connected: true,
2017-11-30T00:44:31.742374+00:00 app[web.1]:         _objectStores: [Map],
2017-11-30T00:44:31.742374+00:00 app[web.1]:         _objectStoreBackends: [Array],
2017-11-30T00:44:31.742375+00:00 app[web.1]:         _db: [EventEmitter] },
2017-11-30T00:44:31.742375+00:00 app[web.1]:      _stateStack: [],
2017-11-30T00:44:31.742376+00:00 app[web.1]:      _txBaseStates: Map { 42399 => 'backend' },
2017-11-30T00:44:31.742377+00:00 app[web.1]:      _transactions: Map { 'backend' => [LevelDBBackend], 42399 => [Circular] },
2017-11-30T00:44:31.742377+00:00 app[web.1]:      _openTransactions: Map { 'backend' => [Set] },
2017-11-30T00:44:31.742378+00:00 app[web.1]:      _closedBaseStates: Set {},
2017-11-30T00:44:31.742378+00:00 app[web.1]:      _snapshotManager: SnapshotManager { _snapshots: Set {} } },
2017-11-30T00:44:31.742379+00:00 app[web.1]:   __backend: 
2017-11-30T00:44:31.742380+00:00 app[web.1]:    LevelDBBackend {
2017-11-30T00:44:31.742380+00:00 app[web.1]:      _db: 
2017-11-30T00:44:31.742381+00:00 app[web.1]:       ConsensusDB {
2017-11-30T00:44:31.742381+00:00 app[web.1]:         _databaseDir: 'full-consensus/',
2017-11-30T00:44:31.742382+00:00 app[web.1]:         _dbVersion: 3,
2017-11-30T00:44:31.742382+00:00 app[web.1]:         _onUpgradeNeeded: undefined,
2017-11-30T00:44:31.742383+00:00 app[web.1]:         _connected: true,
2017-11-30T00:44:31.742384+00:00 app[web.1]:         _objectStores: [Map],
2017-11-30T00:44:31.742384+00:00 app[web.1]:         _objectStoreBackends: [Array],
2017-11-30T00:44:31.742385+00:00 app[web.1]:         _db: [EventEmitter] },
2017-11-30T00:44:31.742386+00:00 app[web.1]:      _tableName: 'Accounts',
2017-11-30T00:44:31.742386+00:00 app[web.1]:      _indices: Map {},
2017-11-30T00:44:31.742387+00:00 app[web.1]:      _codec: AccountsTreeStoreCodec {},
2017-11-30T00:44:31.742387+00:00 app[web.1]:      _dbBackend: 
2017-11-30T00:44:31.742388+00:00 app[web.1]:       EventEmitter {
2017-11-30T00:44:31.742388+00:00 app[web.1]:         domain: null,
2017-11-30T00:44:31.742389+00:00 app[web.1]:         _events: {},
2017-11-30T00:44:31.742389+00:00 app[web.1]:         _eventsCount: 0,
2017-11-30T00:44:31.742390+00:00 app[web.1]:         _maxListeners: undefined,
2017-11-30T00:44:31.742391+00:00 app[web.1]:         sublevels: {},
2017-11-30T00:44:31.742392+00:00 app[web.1]:         options: [Object],
2017-11-30T00:44:31.742392+00:00 app[web.1]:         version: '6.6.1',
2017-11-30T00:44:31.742393+00:00 app[web.1]:         methods: {},
2017-11-30T00:44:31.742393+00:00 app[web.1]:         put: [Function],
2017-11-30T00:44:31.742394+00:00 app[web.1]:         prefix: [Function],
2017-11-30T00:44:31.742394+00:00 app[web.1]:         del: [Function],
2017-11-30T00:44:31.742395+00:00 app[web.1]:         batch: [Function],
2017-11-30T00:44:31.742395+00:00 app[web.1]:         get: [Function],
2017-11-30T00:44:31.742396+00:00 app[web.1]:         clone: [Function],
2017-11-30T00:44:31.742397+00:00 app[web.1]:         sublevel: [Function],
2017-11-30T00:44:31.742397+00:00 app[web.1]:         pre: [Function],
2017-11-30T00:44:31.742398+00:00 app[web.1]:         post: [Function],
2017-11-30T00:44:31.742399+00:00 app[web.1]:         createReadStream: [Function],
2017-11-30T00:44:31.742399+00:00 app[web.1]:         readStream: [Function],
2017-11-30T00:44:31.742400+00:00 app[web.1]:         createValueStream: [Function],
2017-11-30T00:44:31.742400+00:00 app[web.1]:         valueStream: [Function],
2017-11-30T00:44:31.742401+00:00 app[web.1]:         createKeyStream: [Function],
2017-11-30T00:44:31.742401+00:00 app[web.1]:         keyStream: [Function],
2017-11-30T00:44:31.742402+00:00 app[web.1]:         close: [Function],
2017-11-30T00:44:31.742403+00:00 app[web.1]:         isOpen: [Function: isOpen],
2017-11-30T00:44:31.742403+00:00 app[web.1]:         isClosed: [Function: isClosed],
2017-11-30T00:44:31.742404+00:00 app[web.1]:         location: 'full-consensus/' } },
2017-11-30T00:44:31.742404+00:00 app[web.1]:   _commitBackend: 
2017-11-30T00:44:31.742405+00:00 app[web.1]:    ObjectStore {
2017-11-30T00:44:31.742406+00:00 app[web.1]:      __backend: 
2017-11-30T00:44:31.742406+00:00 app[web.1]:       LevelDBBackend {
2017-11-30T00:44:31.742407+00:00 app[web.1]:         _db: [ConsensusDB],
2017-11-30T00:44:31.742407+00:00 app[web.1]:         _tableName: 'Accounts',
2017-11-30T00:44:31.742408+00:00 app[web.1]:         _indices: Map {},
2017-11-30T00:44:31.742408+00:00 app[web.1]:         _codec: AccountsTreeStoreCodec {},
2017-11-30T00:44:31.742409+00:00 app[web.1]:         _dbBackend: [EventEmitter] },
2017-11-30T00:44:31.742410+00:00 app[web.1]:      _db: 
2017-11-30T00:44:31.742410+00:00 app[web.1]:       ConsensusDB {
2017-11-30T00:44:31.742411+00:00 app[web.1]:         _databaseDir: 'full-consensus/',
2017-11-30T00:44:31.742412+00:00 app[web.1]:         _dbVersion: 3,
2017-11-30T00:44:31.742412+00:00 app[web.1]:         _onUpgradeNeeded: undefined,
2017-11-30T00:44:31.742413+00:00 app[web.1]:         _connected: true,
2017-11-30T00:44:31.742413+00:00 app[web.1]:         _objectStores: [Map],
2017-11-30T00:44:31.742414+00:00 app[web.1]:         _objectStoreBackends: [Array],
2017-11-30T00:44:31.742415+00:00 app[web.1]:         _db: [EventEmitter] },
2017-11-30T00:44:31.742415+00:00 app[web.1]:      _stateStack: [],
2017-11-30T00:44:31.742416+00:00 app[web.1]:      _txBaseStates: Map { 42399 => 'backend' },
2017-11-30T00:44:31.742417+00:00 app[web.1]:      _transactions: Map { 'backend' => [LevelDBBackend], 42399 => [Circular] },
2017-11-30T00:44:31.742417+00:00 app[web.1]:      _openTransactions: Map { 'backend' => [Set] },
2017-11-30T00:44:31.742418+00:00 app[web.1]:      _closedBaseStates: Set {},
2017-11-30T00:44:31.742418+00:00 app[web.1]:      _snapshotManager: SnapshotManager { _snapshots: Set {} } },
2017-11-30T00:44:31.742419+00:00 app[web.1]:   _modified: Map {},
2017-11-30T00:44:31.742420+00:00 app[web.1]:   _removed: Set {},
2017-11-30T00:44:31.742420+00:00 app[web.1]:   _originalValues: Map {},
2017-11-30T00:44:31.742421+00:00 app[web.1]:   _truncated: false,
2017-11-30T00:44:31.742421+00:00 app[web.1]:   _indices: Map {},
2017-11-30T00:44:31.742422+00:00 app[web.1]:   _state: 0,
2017-11-30T00:44:31.742422+00:00 app[web.1]:   _nested: Set {},
2017-11-30T00:44:31.742423+00:00 app[web.1]:   _nestedCommitted: false,
2017-11-30T00:44:31.742423+00:00 app[web.1]:   _dependency: null,
2017-11-30T00:44:31.742424+00:00 app[web.1]:   _snapshotManager: SnapshotManager { _snapshots: Set {} },
2017-11-30T00:44:31.742424+00:00 app[web.1]:   _enableWatchdog: true,
2017-11-30T00:44:31.742425+00:00 app[web.1]:   _watchdog: 
2017-11-30T00:44:31.742426+00:00 app[web.1]:    Timeout {
2017-11-30T00:44:31.742426+00:00 app[web.1]:      _called: true,
2017-11-30T00:44:31.742427+00:00 app[web.1]:      _idleTimeout: 10000,
2017-11-30T00:44:31.742427+00:00 app[web.1]:      _idlePrev: null,
2017-11-30T00:44:31.742428+00:00 app[web.1]:      _idleNext: null,
2017-11-30T00:44:31.742428+00:00 app[web.1]:      _idleStart: 629382,
2017-11-30T00:44:31.742429+00:00 app[web.1]:      _onTimeout: [Function],
2017-11-30T00:44:31.742429+00:00 app[web.1]:      _timerArgs: undefined,
2017-11-30T00:44:31.742430+00:00 app[web.1]:      _repeat: null,
2017-11-30T00:44:31.742431+00:00 app[web.1]:      _destroyed: false,
2017-11-30T00:44:31.742431+00:00 app[web.1]:      [Symbol(asyncId)]: 101250,
2017-11-30T00:44:31.742432+00:00 app[web.1]:      [Symbol(triggerAsyncId)]: 0 } }
2017-11-30T00:44:32.117432+00:00 app[web.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 21): Transaction already closed
2017-11-30T00:44:32.117442+00:00 app[web.1]:     at emitWarning (internal/process/promises.js:63:21)
2017-11-30T00:44:32.117443+00:00 app[web.1]:     at emitPendingUnhandledRejections (internal/process/promises.js:95:11)
2017-11-30T00:44:32.117444+00:00 app[web.1]:     at runMicrotasksCallback (internal/process/next_tick.js:124:9)
2017-11-30T00:44:32.117445+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:131:7)
2017-11-30T00:44:32.117445+00:00 app[web.1]:     at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by sisou** [comment]
It looks like it's mining it's own little branch then, not synced to the rest of the network.

**Comment by jsappme** [comment]
Any idea what causes this?

`
Watchdog timer aborted transaction Transaction {...`

**Comment by paberr** [comment]
This may happen when applying a block takes too long (>15 seconds).
Perhaps your system is under heavy load (e.g., mining with too many threads).

**Comment by jsappme** [comment]
I am still getting this error even so my system is not under heavy load.

**Comment by jsappme** [comment]
The error occurs when the miner get overflooded with those:

```
2017-12-02T14:37:31.330683+00:00 app[web.1]: [V 14:37:31] Mempool: Ignoring known transaction X9xzyqqwgRMpRgwIrolW39FYYDAEcX+jP+/Op3AejFA=
2017-12-02T14:37:31.330833+00:00 app[web.1]: [V 14:37:31] Mempool: Ignoring known transaction T1/h4G5oTXfnAbj3qeHgpz9w16iEaZA4peS9vnUV7nA=
2017-12-02T14:37:31.532463+00:00 app[web.1]: [D 14:37:31] Mempool: Delaying transaction - nonce suggests future validity Transaction{senderPubKey=QiWrQv+IUxVFHCPQ3aOp2X68enuItVvlgeplK/0W1K8=, recipientAddr=VPxTnzI18TNkgZCYZSpcx/fO5R0=, value=100000000, fee=0, nonce=99, signature=JUgy07B9M3xu9nBajJzu+R6N9aFIDPE5aPk/m0KXhsqZPChrpBjwGLBgBpgyRchEZuRdUSfjvHkNg4GrgLtbAw==}
2017-12-02T14:37:31.533623+00:00 app[web.1]: [V 14:37:31] Mempool: Ignoring known transaction 9xEnUKo6Xi0icLRSPe5xBfuJocmmXueGFNv2anJj4/g=
2017-12-02T14:37:31.535378+00:00 app[web.1]: [V 14:37:31] Mempool: Ignoring known transaction RhxMD21nTS0Pb3VHEywlW4N3ufOV+7Om+sLeofRcPpU=
2017-12-02T14:37:31.537665+00:00 app[web.1]: [V 14:37:31] Mempool: Ignoring known transaction vaJFHP1LJanTTegm8+RVogW8cdeK9902JYAxEjYghcg=
2017-12-02T14:37:31.554348+00:00 app[web.1]: [D 14:37:31] Mempool: Delaying transaction - nonce suggests future validity Transaction{senderPubKey=QiWrQv+IUxVFHCPQ3aOp2X68enuItVvlgeplK/0W1K8=, recipientAddr=WSvWZVluWA2V0X7dwCEp74zOYvM=, value=100000000, fee=0, nonce=343, signature=ytwzCoX7xKw1urc9YpVhzPtf0nNugllhkZTm/4x8nWqTl8v4g+wt4saJo1JCsujlwEI8pVkF9wKQlKiYn1fnBw==}
2017-12-02T14:37:31.556297+00:00 app[web.1]: [V 14:37:31] Mempool: Ignoring known transaction I59ug/FHANsz4afFNDbm2UAJBvo9CAEiX9GnUaq9a7s=
2017-12-02T14:37:31.722775+00:00 app[web.1]: [D 14:37:31] Mempool: Delaying transaction - nonce suggests future validity Transaction{senderPubKey=QiWrQv+IUxVFHCPQ3aOp2X68enuItVvlgeplK/0W1K8=, recipientAddr=W3Sxh5e3lNk/GoMxkplljsGdlm4=, value=100000000, fee=0, nonce=322, signature=bv84iGNut1DNUAByQkNnAuBt77eiopiAJVYpkdxb62prfQgPtY5QxqLHnAuGtsBDSLYyohhRDcTq6HnAVuDnDQ==}
2017-12-02T14:37:31.779995+00:00 app[web.1]: [D 14:37:31] Mempool: Delaying transaction - nonce suggests future validity Transaction{senderPubKey=QiWrQv+IUxVFHCPQ3aOp2X68enuItVvlgeplK/0W1K8=, recipientAddr=W3yP0Q+5A4Fr9UDE/5OyiYRoBAw=, value=100000000, fee=0, nonce=298, signature=Zw/1MRtpYvwlxIrPzI9HxPDAejwAdmlvDeuvjJz2YC71a3FmYirqvSZiI3fnamzLr4s1aDX+6IWyRsGFtwSsAQ==}
2017-12-02T14:37:31.909669+00:00 app[web.1]: [D 14:37:31] Mempool: Delaying transaction - nonce suggests future validity Transaction{senderPubKey=QiWrQv+IUxVFHCPQ3aOp2X68enuItVvlgeplK/0W1K8=, recipientAddr=XMYFjcDydqJt2diHafAWZWCJSXw=, value=100000000, fee=0, nonce=224, signature=pDGGtn6aY3JwDG6a1cva3vmepBF8jXesQbofbSGdp+2mR2tWdCZXaEkVbQ3QTdxutr3TB3xVJwr0Gd9rMWX/DQ==}
2017-12-02T14:37:32.013606+00:00 app[web.1]: [D 14:37:32] Mempool: Delaying transaction - nonce suggests future validity Transaction{senderPubKey=QiWrQv+IUxVFHCPQ3aOp2X68enuItVvlgeplK/0W1K8=, recipientAddr=XfAOgf6ikCjyHrMf6zKxNvhJOeI=, value=100000000, fee=0, nonce=208, signature=lE17izBRwns3uH+JWfW/TWDR7nuEZeEpvDcjmAlenB2AOWhAWRCGjq37JLRPE46+kENO6myGHYkoHkCo1ac/CA==}
2017-12-02T14:37:32.089404+00:00 app[web.1]: [D 14:37:32] Mempool: Delaying transaction - nonce suggests future validity Transaction{senderPubKey=QiWrQv+IUxVFHCPQ3aOp2X68enuItVvlgeplK/0W1K8=, recipientAddr=Xk1fap/TPtFoWjK34i0Id1uFJW0=, value=100000000, fee=0, nonce=323, signature=HPwLvPeP1kJgkE8wwrPSGNeIAX/YZ32/xa5coCaYmpZSY3tx9pzXJKF2w9pOdbIg6C7f20ulTl5i/T3VYprOBw==}
2017-12-02T14:37:32.173241+00:00 app[web.1]: Watchdog timer aborted transaction Transaction {
```

**Comment by sisou** [comment]
I just had this issue again with Luna v2:
```
Watchdog timer aborted transaction Transaction {
  _id: 49,
  _objectStore: 
   ObjectStore {
     __backend: 
      LevelDBBackend {
        _db: [ConsensusDB],
        _tableName: 'Accounts',
        _indices: Map {},
        _codec: AccountsTreeStoreCodec {},
        _dbBackend: [EventEmitter] },
     _db: 
      ConsensusDB {
        _databaseDir: 'light-consensus/',
        _dbVersion: 3,
        _onUpgradeNeeded: undefined,
        _connected: true,
        _objectStores: [Map],
        _objectStoreBackends: [Array],
        _objectStoresToDelete: [],
        _db: [EventEmitter] },
     _stateStack: [],
     _txBaseStates: Map { 49 => 'backend' },
     _transactions: Map { 'backend' => [LevelDBBackend], 49 => [Circular] },
     _openTransactions: Map { 'backend' => [Set] },
     _closedBaseStates: Set {},
     _snapshotManager: SnapshotManager { _snapshots: Set {} } },
  __backend: 
   LevelDBBackend {
     _db: 
      ConsensusDB {
        _databaseDir: 'light-consensus/',
        _dbVersion: 3,
        _onUpgradeNeeded: undefined,
        _connected: true,
        _objectStores: [Map],
        _objectStoreBackends: [Array],
        _objectStoresToDelete: [],
        _db: [EventEmitter] },
     _tableName: 'Accounts',
     _indices: Map {},
     _codec: AccountsTreeStoreCodec {},
     _dbBackend: 
      EventEmitter {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        sublevels: {},
        options: [Object],
        version: '6.6.1',
        methods: {},
        put: [Function],
        prefix: [Function],
        del: [Function],
        batch: [Function],
        get: [Function],
        clone: [Function],
        sublevel: [Function],
        pre: [Function],
        post: [Function],
        createReadStream: [Function],
        readStream: [Function],
        createValueStream: [Function],
        valueStream: [Function],
        createKeyStream: [Function],
        keyStream: [Function],
        close: [Function],
        isOpen: [Function: isOpen],
        isClosed: [Function: isClosed],
        location: 'light-consensus/' } },
  _commitBackend: 
   ObjectStore {
     __backend: 
      LevelDBBackend {
        _db: [ConsensusDB],
        _tableName: 'Accounts',
        _indices: Map {},
        _codec: AccountsTreeStoreCodec {},
        _dbBackend: [EventEmitter] },
     _db: 
      ConsensusDB {
        _databaseDir: 'light-consensus/',
        _dbVersion: 3,
        _onUpgradeNeeded: undefined,
        _connected: true,
        _objectStores: [Map],
        _objectStoreBackends: [Array],
        _objectStoresToDelete: [],
        _db: [EventEmitter] },
     _stateStack: [],
     _txBaseStates: Map { 49 => 'backend' },
     _transactions: Map { 'backend' => [LevelDBBackend], 49 => [Circular] },
     _openTransactions: Map { 'backend' => [Set] },
     _closedBaseStates: Set {},
     _snapshotManager: SnapshotManager { _snapshots: Set {} } },
  _modified: Map {},
  _removed: Set {},
  _originalValues: Map {},
  _truncated: false,
  _indices: Map {},
  _state: 0,
  _nested: Set {},
  _nestedCommitted: false,
  _dependency: null,
  _snapshotManager: SnapshotManager { _snapshots: Set {} },
  _enableWatchdog: true,
  _watchdog: 
   Timeout {
     _called: true,
     _idleTimeout: 10000,
     _idlePrev: null,
     _idleNext: null,
     _idleStart: 518519,
     _onTimeout: [Function],
     _timerArgs: undefined,
     _repeat: null,
     _destroyed: false,
     [Symbol(asyncId)]: 6117,
     [Symbol(triggerAsyncId)]: 0 } }
(node:22794) UnhandledPromiseRejectionWarning: Error: Invalid block body: undefined
    at Miner._getNextHeader (/home/users/soeren/github/nimiq-core/dist/node.js:1:248547)
    at <anonymous>
    at emitWarning (internal/process/promises.js:65:17)
    at emitPendingUnhandledRejections (internal/process/promises.js:109:11)
    at runMicrotasksCallback (internal/process/next_tick.js:118:9)
    at process._tickCallback (internal/process/next_tick.js:150:11)
(node:22794) Error: Invalid block body: undefined
    at Miner._getNextHeader (/home/users/soeren/github/nimiq-core/dist/node.js:1:248547)
    at <anonymous>
(node:22794) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitWarning (internal/process/promises.js:92:15)
    at emitPendingUnhandledRejections (internal/process/promises.js:109:11)
    at runMicrotasksCallback (internal/process/next_tick.js:118:9)
    at process._tickCallback (internal/process/next_tick.js:150:11)
```
**Note:** I am running as localhost:8080. The last logout was `FullChain: Ignoring known block xAjioPVbNvbGglpSRduJKh+wZgXbeqUS7oZXIk2Nn7Q=` 9 seconds before. There was no further log output after the error.

**Comment by sisou** [comment]
I agree that the reason is maybe that the system is under too heavy load and the DB does not react fast enough, but at least the exception should be caught at the correct point and maybe retried, instead of soft-crashing the process.

**Comment by sisou** [comment]
I'm also now getting `Transaction stack size exceeded` errors, without any more info and no usable stack trace. I'm running node 9.3.0, by the way.

**Comment by paberr** [comment]
I also got these exceptions yesterday. It is a consequence of the watchdog timer exception.
The issue is already on my todo list (and I'll probably fix it today).

**Comment by paberr** [comment]
The newest version of the JungleDB now only logs warnings instead of aborting transactions.
Hence, commit bd8321699005603ad7d9909475afef2c1e9d2b61 should fix this issue.
