### ISSUE TITLE
Error displaying miner hashrate

### ISSUE THREAD

**Issue by tomkha** [nimiq-network/core#346]
I've got this once while running miner in NodeJS

```
RangeError: toFixed() digits argument must be between 0 and 20
    at Number.toFixed (<anonymous>)
    at $.miner.on (/home/ubuntu/nimiq/clients/nodejs/index.js:226:72)
    at <anonymous>
(node:4709) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitWarning (internal/process/promises.js:78:15)
    at emitPendingUnhandledRejections (internal/process/promises.js:95:11)
    at runMicrotasksCallback (internal/process/next_tick.js:124:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by paberr** [comment]
Was fixed in fed8807af8b71b23ab505db945b98155fc9a52ae.
