### ISSUE TITLE
Node.js client: SyntaxError: Unexpected token (

### ISSUE THREAD

**Issue by Smittyvb** [nimiq-network/core#372]
## General information

- Library version(s): master branch
- Devices/Simulators/Machine affected: Windows 10, node v6.9.2
- Reproducible in the testnet? (Yes/No): Yes

#### Expected behavior
Nimiq node launches.

#### Actual behavior
I get this error: 
```js
(async () => {
       ^
SyntaxError: Unexpected token (
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

#### Steps to reproduce
Run:
```cmd
cd clients/nodejs
node index
```

**Comment by paberr** [comment]
We only support NodeJS version 8.0.0 and above.
From our README:
```
Install Node.js v8.0.0 or higher.
```
