### ISSUE TITLE
Error when I run the core on Ubuntu

### ISSUE THREAD

**Issue by elshorbagy** [nimiq-network/core#389]
Hello,

I used this command to install and run nodejs and the core
`sudo apt update -y && sudo apt upgrade -y && sudo curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash - && sudo apt install -y nodejs && sudo apt install -y git && sudo apt install -y build-essential && sudo npm install -g pm2 && sudo npm install -g gulp && sudo npm install -g yarn && git clone https://github.com/nimiq-network/core && cd core && sudo yarn && cd clients/nodejs && THREADS=$(grep -c ^processor /proc/cpuinfo) && NAME=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 13 ; echo '') && env UV_THREADPOOL_SIZE=${THREADS} pm2 start index.js -- --dumb --miner=${THREADS} --statistics=10 --wallet-address='my wallet address" --extra-data=${NAME}`

But after the installation, Index,js could not run. This the pm2 log file:

> 0|index    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
0|index    |     at Module.load (internal/modules/cjs/loader.js:566:32)
0|index    |     at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
0|index    |     at Function.Module._load (internal/modules/cjs/loader.js:498:3)
0|index    | Error: Cannot find module 'minimist'
0|index    |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
0|index    |     at Function.Module._load (internal/modules/cjs/loader.js:475:25)
0|index    |     at Module.require (internal/modules/cjs/loader.js:598:17)
0|index    |     at require (internal/modules/cjs/helpers.js:11:18)
0|index    |     at Object.<anonymous> (/home/elshorbgy/core/clients/nodejs/index.js:2:14)
0|index    |     at Module._compile (internal/modules/cjs/loader.js:654:30)
0|index    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
0|index    |     at Module.load (internal/modules/cjs/loader.js:566:32)
0|index    |     at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
0|index    |     at Function.Module._load (internal/modules/cjs/loader.js:498:3)

Thank you

**Comment by lkraider** [comment]
Looks like a permission issue. Try to run yarn without sudo.
